# Generated by Django 5.2.16 on 2026-07-30 23:23

import core.constraints
import core.models
import django.db.models.deletion
import django.db.models.functions.text
import phonenumber_field.modelfields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0002_seed_languages'),
        ('org', '0003_alter_assignment_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='time updated')),
                ('name', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for signup'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='org.ministry')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events_owned', to='contact.contact')),
            ],
            options={
                'ordering': ['-start_time'],
            },
            bases=(core.constraints.ConstraintErrorFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EventRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='time updated')),
                ('needed_count', models.PositiveIntegerField(blank=True, help_text='Leave empty for no limit. Advisory only — signups are never blocked.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='events.event')),
            ],
            options={
                'ordering': ['event', 'role__name'],
            },
            bases=(core.constraints.ConstraintErrorFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Stable identifier used by code. Lowercase, cannot be changed later.')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='eventtype_code_ci_unique', violation_error_code='eventtype_code_taken', violation_error_message='An event type with this code already exists.')],
            },
            bases=(core.models.ImmutableCodeMixin, core.constraints.ConstraintErrorFieldMixin, models.Model),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.eventtype'),
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='time created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='time updated')),
                ('name', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for signup'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('event_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.eventtype')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='org.ministry')),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contact.contact')),
            ],
            options={
                'verbose_name': 'historical event',
                'verbose_name_plural': 'historical events',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalParticipation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='time created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='time updated')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('absent', 'No-show'), ('cancelled', 'Cancelled')], default='registered', max_length=20)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('consent_given_by', models.CharField(blank=True, max_length=200)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('consent_method', models.CharField(blank=True, choices=[('verbal', '口头'), ('paper', '纸质'), ('online', '线上')], max_length=20)),
                ('consent_email', models.EmailField(blank=True, max_length=254)),
                ('consent_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='US')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('consent_relationship', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'usable_as_emergency_contact': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contact.relationshiptype')),
                ('contact', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contact.contact')),
                ('event_role', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.eventrole')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical participation',
                'verbose_name_plural': 'historical participations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='time updated')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('absent', 'No-show'), ('cancelled', 'Cancelled')], default='registered', max_length=20)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('consent_given_by', models.CharField(blank=True, max_length=200)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('consent_method', models.CharField(blank=True, choices=[('verbal', '口头'), ('paper', '纸质'), ('online', '线上')], max_length=20)),
                ('consent_email', models.EmailField(blank=True, max_length=254)),
                ('consent_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='US')),
                ('consent_relationship', models.ForeignKey(blank=True, limit_choices_to={'usable_as_emergency_contact': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contact.relationshiptype')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='contact.contact')),
                ('event_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='events.eventrole')),
            ],
            options={
                'ordering': ['-registered_at', 'contact'],
            },
            bases=(core.constraints.ConstraintErrorFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ParticipationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Stable identifier used by code. Lowercase, cannot be changed later.')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='participationrole_code_ci_unique', violation_error_code='participationrole_code_taken', violation_error_message='A participation role with this code already exists.')],
            },
            bases=(core.models.ImmutableCodeMixin, core.constraints.ConstraintErrorFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEventRole',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='time created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='time updated')),
                ('needed_count', models.PositiveIntegerField(blank=True, help_text='Leave empty for no limit. Advisory only — signups are never blocked.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.event')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.participationrole')),
            ],
            options={
                'verbose_name': 'historical event role',
                'verbose_name_plural': 'historical event roles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='eventrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='events.participationrole'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_time'], name='events_even_start_t_c2d277_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['ministry', 'start_time'], name='events_even_ministr_eeca3d_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'start_time'], name='events_even_status_189ced_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gte', models.F('start_time'))), name='event_end_time_not_before_start_time', violation_error_code='event_end_before_start', violation_error_message='The end time cannot be before the start time.'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('event_role', 'contact'), name='participation_unique_per_event_role', violation_error_code='participation_duplicate', violation_error_message='They are already signed up for this role.'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.CheckConstraint(condition=models.Q(('hours__isnull', True), ('hours__gte', 0), _connector='OR'), name='participation_hours_not_negative', violation_error_code='participation_hours_negative', violation_error_message='Hours cannot be negative.'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'attended'), ('hours__isnull', True), ('hours', 0), _connector='OR'), name='participation_hours_only_when_attended', violation_error_code='participation_hours_without_attendance', violation_error_message='Only somebody recorded as having attended can have hours.'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.CheckConstraint(condition=models.Q(('checked_out_at__isnull', True), ('checked_in_at__isnull', True), ('checked_out_at__gte', models.F('checked_in_at')), _connector='OR'), name='participation_checkout_after_checkin', violation_error_code='participation_checkout_before_checkin', violation_error_message='Check-out cannot be before check-in.'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.CheckConstraint(condition=models.Q(('checked_in_at__isnull', True), models.Q(('status', 'absent'), _negated=True), _connector='OR'), name='participation_checked_in_is_not_absent', violation_error_code='participation_absent_after_checkin', violation_error_message='Somebody who checked in cannot be marked absent.'),
        ),
        migrations.AddConstraint(
            model_name='eventrole',
            constraint=models.UniqueConstraint(fields=('event', 'role'), name='eventrole_unique_per_event', violation_error_code='eventrole_duplicate', violation_error_message='This event already has that role open.'),
        ),
        migrations.AddConstraint(
            model_name='eventrole',
            constraint=models.CheckConstraint(condition=models.Q(('needed_count__isnull', True), ('needed_count__gt', 0), _connector='OR'), name='eventrole_needed_count_is_positive', violation_error_code='eventrole_needed_count_not_positive', violation_error_message='Leave the number empty for no limit; otherwise it has to be at least 1.'),
        ),
    ]
