# Generated by Django 5.2.16 on 2026-07-31 01:05

import core.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='time updated')),
                ('reason', models.CharField(choices=[('time_changed', 'Time changed'), ('location_changed', 'Location changed'), ('cancelled', 'Event cancelled'), ('other', 'Other')], max_length=30)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField()),
                ('provider_ref', models.CharField(blank=True, max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.event')),
                ('recipients', models.ManyToManyField(blank=True, related_name='notifications', to='events.participation')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unreachable', models.ManyToManyField(blank=True, related_name='notifications_unreachable', to='events.participation')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['event', '-sent_at'], name='events_even_event_i_86206d_idx')],
            },
            bases=(core.constraints.ConstraintErrorFieldMixin, models.Model),
        ),
    ]
