# Generated by Django 5.2.16 on 2026-08-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_seed_general_participation_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requires_guardian_consent',
            field=models.BooleanField(default=True, help_text='Untick only when under-18s may sign up on their own, like an adult. Ticked, they need consent on file and somebody to call.', verbose_name="Minors need a guardian's consent"),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='requires_guardian_consent',
            field=models.BooleanField(default=True, help_text='Untick only when under-18s may sign up on their own, like an adult. Ticked, they need consent on file and somebody to call.', verbose_name="Minors need a guardian's consent"),
        ),
    ]
