# Generated by Django 5.2.16 on 2026-08-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_general_role_name_in_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparticipation',
            name='consent_method',
            field=models.CharField(blank=True, choices=[('verbal', 'In person'), ('paper', 'On paper'), ('online', 'Online')], max_length=20),
        ),
        migrations.AlterField(
            model_name='participation',
            name='consent_method',
            field=models.CharField(blank=True, choices=[('verbal', 'In person'), ('paper', 'On paper'), ('online', 'Online')], max_length=20),
        ),
    ]
