# Generated by Django 5.2.16 on 2026-08-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_consent_method_labels_in_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='event-images'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='image',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
