# Generated by Django 5.2.16 on 2026-08-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_text_length_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparticipation',
            name='checked_in_method',
            field=models.CharField(blank=True, choices=[('admin', 'Recorded by an admin'), ('self_qr', 'Self check-in by QR')], max_length=20),
        ),
        migrations.AddField(
            model_name='participation',
            name='checked_in_method',
            field=models.CharField(blank=True, choices=[('admin', 'Recorded by an admin'), ('self_qr', 'Self check-in by QR')], max_length=20),
        ),
    ]
