# Generated by Django 5.2.16 on 2026-08-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_historicalparticipation_checked_in_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventnotification',
            name='failed',
            field=models.ManyToManyField(blank=True, related_name='notifications_failed', to='events.participation'),
        ),
    ]
