"""「Confirmed」改叫「Full」，**连库里存的值一起改**（2026-08-19）。

⚠️ 只改标签不改值，是这个项目反复在付账的那种漂移：页面上写 Full、数据库里
   存 confirmed，下一个人读数据（或读一行日志）学到的是一个界面里根本不存在的词。

⚠️ 历史表也要改。`Event` 挂着 simple-history，`events_historicalevent` 里同样
   躺着 `confirmed`。漏掉它的表现是：活动本身好好的，而它的历史记录页上那一行
   写着一个不在选项里的状态 —— 而且那一页没人天天看，所以会烂很久。

⚠️ 逆向写全了。回滚这条迁移而不把值改回去，会留下一列 `full`，
   而那时候的 choices 里没有这个值 —— 一个不报错、只是到处显示空白的状态。
"""

# Generated by Django 5.2.16 on 2026-08-19 22:53

from django.db import migrations, models


def confirmed_to_full(apps, schema_editor):
    for label in ("Event", "HistoricalEvent"):
        apps.get_model("events", label).objects.filter(
            status="confirmed").update(status="full")


def full_to_confirmed(apps, schema_editor):
    for label in ("Event", "HistoricalEvent"):
        apps.get_model("events", label).objects.filter(
            status="full").update(status="confirmed")


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventnotification_failed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for signup'), ('full', 'Full'), ('completed', 'Wrapped up'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for signup'), ('full', 'Full'), ('completed', 'Wrapped up'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.RunPython(confirmed_to_full, full_to_confirmed),
    ]
