"""角色上的「到这个人数就停止报名」（2026-08-19）。

⚠️ **默认 True，也就是说这条迁移会给每一个既有角色装上一个上限。** 那是有意的：
   在这个字段之前，`needed_count` 只喂报表，**没有任何地方拦过报名** ——
   一个只要 5 个人的活儿能报进 50 个，而这件事直到活动当天早上才看得见。

   反过来的默认（不拦）失败得更安静，所以选了这个方向；同
   `Event.requires_guardian_consent` 那条注释里写全的那套判据。

⚠️ 代价说明白：已经**超额**的既有角色，从此报不进新人（历史报名不受影响，
   一行都不会删）。想继续多多益善的活儿，把那个勾去掉 —— 那正是这个字段存在的
   理由：基金会要的是「我们需要 500 人，但越多越好」。

⚠️ `needed_count` 的 help_text 同时改了：原文是「Advisory only — signups are
   never blocked」，那句话从这条迁移起就不再是真的了。
"""

# Generated by Django 5.2.16 on 2026-08-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_status_alter_historicalevent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrole',
            name='stop_at_needed_count',
            field=models.BooleanField(default=True, help_text='Untick if more people than that are welcome — the number then says what you are aiming for, and nobody is refused.', verbose_name='Stop signups at this number'),
        ),
        migrations.AddField(
            model_name='historicaleventrole',
            name='stop_at_needed_count',
            field=models.BooleanField(default=True, help_text='Untick if more people than that are welcome — the number then says what you are aiming for, and nobody is refused.', verbose_name='Stop signups at this number'),
        ),
        migrations.AlterField(
            model_name='eventrole',
            name='needed_count',
            field=models.PositiveIntegerField(blank=True, help_text='How many people this job wants. Leave empty for no limit.', null=True),
        ),
        migrations.AlterField(
            model_name='historicaleventrole',
            name='needed_count',
            field=models.PositiveIntegerField(blank=True, help_text='How many people this job wants. Leave empty for no limit.', null=True),
        ),
    ]
