# Generated by Django 5.2.16 on 2026-08-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_eventrole_stop_at_needed_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparticipation',
            name='served_as',
            field=models.CharField(blank=True, choices=[('volunteer', 'Volunteering'), ('work', 'Scheduled work')], max_length=20),
        ),
        migrations.AddField(
            model_name='historicalparticipation',
            name='served_as_declared_by',
            field=models.CharField(blank=True, choices=[('self', 'Said by the volunteer'), ('admin', 'Set by an admin')], max_length=20),
        ),
        migrations.AddField(
            model_name='participation',
            name='served_as',
            field=models.CharField(blank=True, choices=[('volunteer', 'Volunteering'), ('work', 'Scheduled work')], max_length=20),
        ),
        migrations.AddField(
            model_name='participation',
            name='served_as_declared_by',
            field=models.CharField(blank=True, choices=[('self', 'Said by the volunteer'), ('admin', 'Set by an admin')], max_length=20),
        ),
    ]
