"""L3 / L2: who can see an event, and who can sign up for one of its roles.

Three columns on each of Event and EventRole — outsiders, all staff, named
ministries — replacing nothing, because until now neither had any notion of an
audience at all: every signed-in account saw every published event.

⚠️ The backfill at the end is not optional and belongs in **this** migration.
   Both booleans default to False, so between AddField and a separate data
   migration every event in the database would be visible to nobody. The rows
   are given what they mean today — outsiders **and** all staff, which is what
   "any signed-in account" amounted to.

⚠️ That is not the default new events get. The column default stays False and
   the form refuses an empty audience, so publishing forces a choice; this
   migration is preserving existing behaviour, not setting policy. The two look
   like they contradict each other, which is why they are written down together.

⚠️ The M2M gets its own historical through-tables (simple-history's m2m_fields).
   Without them the two booleans would be in the history and the ministry list
   would not — half a record of who could see this, which reads as a whole one.

See participants.md L2/L3 and 06-roadmap.md L2.1.
"""

# Generated by Django 5.2.16 on 2026-08-26 22:00

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


def open_to_everyone(apps, schema_editor):
    """What every event and role meant before this migration: anybody signed in.

    ⚠️ Both flags, not just `visible_to_outsiders`. Outsiders alone would hide
       every existing event from the foundation's own staff — the opposite of
       what the rows say today, and silent.
    """
    for label in ("Event", "EventRole"):
        apps.get_model("events", label).objects.update(
            visible_to_outsiders=True, visible_to_all_staff=True)


def hide_from_everyone(apps, schema_editor):
    """⚠️ Lossy, and named for what it does rather than for undoing anything.

    Reversing drops the columns, so any audience anybody has since chosen is
    gone. Clearing the flags first is honest about that rather than leaving a
    half-migrated state; the ministry lists go with the tables.
    """
    for label in ("Event", "EventRole"):
        apps.get_model("events", label).objects.update(
            visible_to_outsiders=False, visible_to_all_staff=False)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_second_catch_all_role'),
        ('org', '0008_kind_to_staff_and_compensation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visible_to_all_staff',
            field=models.BooleanField(default=False, help_text='Anyone holding a post on the day — paid or not.', verbose_name='Everybody on the books'),
        ),
        migrations.AddField(
            model_name='event',
            name='visible_to_ministries',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='+', to='org.ministry', verbose_name="Only these ministries' staff"),
        ),
        migrations.AddField(
            model_name='event',
            name='visible_to_outsiders',
            field=models.BooleanField(default=False, help_text='Outside volunteers and the people the foundation serves.', verbose_name='People with no current post'),
        ),
        migrations.AddField(
            model_name='eventrole',
            name='visible_to_all_staff',
            field=models.BooleanField(default=False, help_text='Anyone holding a post on the day — paid or not.', verbose_name='Everybody on the books'),
        ),
        migrations.AddField(
            model_name='eventrole',
            name='visible_to_ministries',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='+', to='org.ministry', verbose_name="Only these ministries' staff"),
        ),
        migrations.AddField(
            model_name='eventrole',
            name='visible_to_outsiders',
            field=models.BooleanField(default=False, help_text='Outside volunteers and the people the foundation serves.', verbose_name='People with no current post'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='visible_to_all_staff',
            field=models.BooleanField(default=False, help_text='Anyone holding a post on the day — paid or not.', verbose_name='Everybody on the books'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='visible_to_outsiders',
            field=models.BooleanField(default=False, help_text='Outside volunteers and the people the foundation serves.', verbose_name='People with no current post'),
        ),
        migrations.AddField(
            model_name='historicaleventrole',
            name='visible_to_all_staff',
            field=models.BooleanField(default=False, help_text='Anyone holding a post on the day — paid or not.', verbose_name='Everybody on the books'),
        ),
        migrations.AddField(
            model_name='historicaleventrole',
            name='visible_to_outsiders',
            field=models.BooleanField(default=False, help_text='Outside volunteers and the people the foundation serves.', verbose_name='People with no current post'),
        ),
        migrations.CreateModel(
            name='HistoricalEvent_visible_to_ministries',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.event')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='events.historicalevent')),
                ('ministry', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='org.ministry')),
            ],
            options={
                'verbose_name': 'HistoricalEvent_visible_to_ministries',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEventRole_visible_to_ministries',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('eventrole', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.eventrole')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='events.historicaleventrole')),
                ('ministry', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='org.ministry')),
            ],
            options={
                'verbose_name': 'HistoricalEventRole_visible_to_ministries',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RunPython(open_to_everyone, hide_from_everyone),
    ]
