# Generated by Django 5.2.16 on 2026-09-05 22:07

import core.constraints
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """L5.1: the meetings inside a run — one Event, many Sessions.

    Two new tables and nothing else. No column on an existing table changes, no
    row is backfilled, and no existing row's meaning moves: every event in the
    database today is a single occasion with no sessions, which is what having
    none of these rows means.

    Reversible with no loss of anything that existed before this migration —
    dropping the tables removes only rows that could not have been written until
    it ran.
    """

    dependencies = [
        ('events', '0021_drop_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSession',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='time created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='time updated')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('source', models.CharField(choices=[('manual', 'Added by hand'), ('generated', 'Produced by a rule')], default='manual', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.event')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical session',
                'verbose_name_plural': 'historical sessions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='time updated')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('source', models.CharField(choices=[('manual', 'Added by hand'), ('generated', 'Produced by a rule')], default='manual', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='events.event')),
            ],
            options={
                'ordering': ['start_time', 'id'],
                'constraints': [models.UniqueConstraint(fields=('event', 'start_time'), name='session_no_two_meetings_at_once', violation_error_code='session_duplicate_start', violation_error_message='This run already has a meeting starting then.'), models.CheckConstraint(condition=models.Q(('end_time__gte', models.F('start_time'))), name='session_end_time_not_before_start_time', violation_error_code='session_end_before_start', violation_error_message='The end time cannot be before the start time.')],
            },
            bases=(core.constraints.ConstraintErrorFieldMixin, models.Model),
        ),
    ]
