# Generated by Django 5.2.16 on 2026-09-08 22:36

import core.constraints
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """L5.2: the register — one person at one meeting.

    Two new tables and nothing else, the same shape as 0022: no column on an
    existing table changes, no row is backfilled, and no existing row's meaning
    moves. Having none of these rows is what today's database already means —
    nobody has been marked present at a meeting, because until now there was
    nowhere to record it.

    ⚠️ No column here holds what somebody **received**. How long the
       foundation's time was spent on a person is worked out from the meeting's
       own two ends (D43), so this migration deliberately adds no column for it.

    Reversible with no loss of anything that existed before it ran.
    """

    dependencies = [
        ('events', '0023_audience_help_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSessionAttendance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='time created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='time updated')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('absent', 'No-show'), ('cancelled', 'Cancelled')], default='registered', max_length=20)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_method', models.CharField(blank=True, choices=[('admin', 'Recorded by an admin'), ('self_qr', 'Self check-in by QR')], max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('participation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.participation')),
                ('session', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.session')),
            ],
            options={
                'verbose_name': 'historical session attendance',
                'verbose_name_plural': 'historical session attendances',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='time updated')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('absent', 'No-show'), ('cancelled', 'Cancelled')], default='registered', max_length=20)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_method', models.CharField(blank=True, choices=[('admin', 'Recorded by an admin'), ('self_qr', 'Self check-in by QR')], max_length=20)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.participation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.session')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participation', 'session'), name='sessionattendance_duplicate', violation_error_code='sessionattendance_duplicate', violation_error_message='They are already on the register for this meeting.'), models.CheckConstraint(condition=models.Q(('hours__isnull', True), ('hours__gte', 0), _connector='OR'), name='sessionattendance_hours_not_negative', violation_error_code='sessionattendance_hours_negative', violation_error_message='Hours cannot be negative.'), models.CheckConstraint(condition=models.Q(('status', 'attended'), ('hours__isnull', True), ('hours', 0), _connector='OR'), name='sessionattendance_hours_only_when_attended', violation_error_code='sessionattendance_hours_without_attendance', violation_error_message='Only somebody recorded as having attended can have hours.'), models.CheckConstraint(condition=models.Q(('checked_out_at__isnull', True), ('checked_in_at__isnull', True), ('checked_out_at__gte', models.F('checked_in_at')), _connector='OR'), name='sessionattendance_checkout_after_checkin', violation_error_code='sessionattendance_checkout_before_checkin', violation_error_message='Check-out cannot be before check-in.'), models.CheckConstraint(condition=models.Q(('checked_in_at__isnull', True), models.Q(('status', 'absent'), _negated=True), _connector='OR'), name='sessionattendance_checked_in_is_not_absent', violation_error_code='sessionattendance_absent_after_checkin', violation_error_message='Somebody who checked in cannot be marked absent.')],
            },
            bases=(core.constraints.ConstraintErrorFieldMixin, models.Model),
        ),
    ]
