# Generated by Django 5.2.16 on 2026-09-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    """A fifth signup status: withdrew partway.

    Choices only — two `AlterField`s, which Postgres executes as a no-op, and
    **no backfill**.

    🔴 The absence of a backfill is the decision. Every existing `cancelled` row
       is one of the two facts, and which one is not recoverable: the register
       that would answer it (`SessionAttendance`) has existed for one day, so no
       historical cancellation has one behind it. Guessing would write an answer
       nobody gave onto rows the annual report reads — the same objection D38
       raised against defaulting `served_as`, arriving on a second column.

    Every row written from now on goes through services.cancel(), which picks
    between the two by asking the register.
    """

    dependencies = [
        ('events', '0024_session_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparticipation',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('absent', 'No-show'), ('cancelled', 'Cancelled'), ('withdrew', 'Withdrew partway')], default='registered', max_length=20),
        ),
        migrations.AlterField(
            model_name='participation',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('absent', 'No-show'), ('cancelled', 'Cancelled'), ('withdrew', 'Withdrew partway')], default='registered', max_length=20),
        ),
    ]
