# Generated by Django 5.2.16 on 2026-09-11 02:20
#
# 06-roadmap L5.4 — recurring events: one rule and one template producing N
# separate events.
#
# ⚠️ **No backfill, and that is checked rather than assumed.** The two columns
#    added to `Event` both have defaults that are true of every row already in
#    the database: nothing was made by a rule before this migration, because
#    there was no rule to make it. Contrast 0027, which *did* have to backfill —
#    L5.1 and L5.2 had been growing courses with meetings for three days before
#    `Event.shape` arrived, so "every event in here is a one-off" had stopped
#    being true before the column existed to say so.
#
# ⚠️ The unique constraint on `(series, start_time)` is **partial**: two events
#    at the same moment are ordinary (two distributions on one Saturday), so it
#    only binds rows a rule made. Nothing existing can violate it, because
#    nothing existing has a series.

import core.constraints
import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_contact_contact_individual_has_a_first_name'),
        ('events', '0027_backfill_event_shape'),
        ('org', '0008_kind_to_staff_and_compensation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSeriesRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='time updated')),
                ('visible_to_outsiders', models.BooleanField(default=False, help_text='People from outside the foundation — including the people it serves.', verbose_name='People with no current post')),
                ('visible_to_all_staff', models.BooleanField(default=False, help_text='Anyone holding a post on the day — paid or not.', verbose_name='Everybody on the books')),
                ('needed_count', models.PositiveIntegerField(blank=True, help_text='How many people this job wants, on each occasion. Leave empty for no limit.', null=True)),
                ('stop_at_needed_count', models.BooleanField(default=True, help_text='Untick if more people than that are welcome — the number then says what you are aiming for, and nobody is refused.', verbose_name='Stop signups at this number')),
                ('notes', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['series', 'role__name'],
            },
            bases=(core.constraints.ConstraintErrorFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEventSeries',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='time created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='time updated')),
                ('visible_to_outsiders', models.BooleanField(default=False, help_text='People from outside the foundation — including the people it serves.', verbose_name='People with no current post')),
                ('visible_to_all_staff', models.BooleanField(default=False, help_text='Anyone holding a post on the day — paid or not.', verbose_name='Everybody on the books')),
                ('name', models.CharField(max_length=200)),
                ('rule', models.TextField(help_text='A repeat rule, e.g. FREQ=WEEKLY;BYDAY=TU;COUNT=12. It has to say when it stops — UNTIL= a date, or COUNT= a number.', max_length=500, verbose_name='How often')),
                ('starts_on', models.DateField(help_text='The date of the first occasion. Later ones follow the rule.', verbose_name='First one on')),
                ('start_time', models.TimeField(verbose_name='Starts at')),
                ('duration', models.DurationField(help_text='How long each occasion lasts, written hours:minutes:seconds — 2:00:00 for two hours.', verbose_name='Runs for')),
                ('image', models.TextField(blank=True, help_text='Shown on every occasion this makes. Change it here and they all change; an occasion with its own picture keeps that one.', max_length=100, verbose_name='Picture')),
                ('location', models.CharField(blank=True, help_text='Copied onto each occasion as it is made. Changing it later does not move occasions that already exist.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Copied onto each occasion as it is made. Changing it later does not reach occasions that already exist.', max_length=2000)),
                ('status', models.CharField(choices=[('draft', 'Drafts — nobody sees them until you publish'), ('open', 'Open for signup')], default='draft', max_length=20, verbose_name='Publish the occasions as')),
                ('requires_guardian_consent', models.BooleanField(default=True, help_text='Applies to every occasion this makes. Untick only when under-18s may sign up on their own, like an adult.', verbose_name="Minors need a guardian's consent")),
                ('ended_on', models.DateField(blank=True, help_text='Set when the series was stopped early. No more occasions are generated from this date onwards; the ones that already happened stay.', null=True, verbose_name='Stopped on')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical event series',
                'verbose_name_plural': 'historical event series',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEventSeries_visible_to_ministries',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'HistoricalEventSeries_visible_to_ministries',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEventSeriesRole',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='time created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='time updated')),
                ('visible_to_outsiders', models.BooleanField(default=False, help_text='People from outside the foundation — including the people it serves.', verbose_name='People with no current post')),
                ('visible_to_all_staff', models.BooleanField(default=False, help_text='Anyone holding a post on the day — paid or not.', verbose_name='Everybody on the books')),
                ('needed_count', models.PositiveIntegerField(blank=True, help_text='How many people this job wants, on each occasion. Leave empty for no limit.', null=True)),
                ('stop_at_needed_count', models.BooleanField(default=True, help_text='Untick if more people than that are welcome — the number then says what you are aiming for, and nobody is refused.', verbose_name='Stop signups at this number')),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical event series role',
                'verbose_name_plural': 'historical event series roles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEventSeriesRole_visible_to_ministries',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'HistoricalEventSeriesRole_visible_to_ministries',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.CharField(choices=[('manual', 'Added by hand'), ('generated', 'Produced by a rule')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='source',
            field=models.CharField(choices=[('manual', 'Added by hand'), ('generated', 'Produced by a rule')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='EventSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='time updated')),
                ('visible_to_outsiders', models.BooleanField(default=False, help_text='People from outside the foundation — including the people it serves.', verbose_name='People with no current post')),
                ('visible_to_all_staff', models.BooleanField(default=False, help_text='Anyone holding a post on the day — paid or not.', verbose_name='Everybody on the books')),
                ('name', models.CharField(max_length=200)),
                ('rule', models.TextField(help_text='A repeat rule, e.g. FREQ=WEEKLY;BYDAY=TU;COUNT=12. It has to say when it stops — UNTIL= a date, or COUNT= a number.', max_length=500, verbose_name='How often')),
                ('starts_on', models.DateField(help_text='The date of the first occasion. Later ones follow the rule.', verbose_name='First one on')),
                ('start_time', models.TimeField(verbose_name='Starts at')),
                ('duration', models.DurationField(help_text='How long each occasion lasts, written hours:minutes:seconds — 2:00:00 for two hours.', verbose_name='Runs for')),
                ('image', models.ImageField(blank=True, help_text='Shown on every occasion this makes. Change it here and they all change; an occasion with its own picture keeps that one.', upload_to='event-images', verbose_name='Picture')),
                ('location', models.CharField(blank=True, help_text='Copied onto each occasion as it is made. Changing it later does not move occasions that already exist.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Copied onto each occasion as it is made. Changing it later does not reach occasions that already exist.', max_length=2000)),
                ('status', models.CharField(choices=[('draft', 'Drafts — nobody sees them until you publish'), ('open', 'Open for signup')], default='draft', max_length=20, verbose_name='Publish the occasions as')),
                ('requires_guardian_consent', models.BooleanField(default=True, help_text='Applies to every occasion this makes. Untick only when under-18s may sign up on their own, like an adult.', verbose_name="Minors need a guardian's consent")),
                ('ended_on', models.DateField(blank=True, help_text='Set when the series was stopped early. No more occasions are generated from this date onwards; the ones that already happened stay.', null=True, verbose_name='Stopped on')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_series_generated', to='contact.contact')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_series', to='org.ministry')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_series_owned', to='contact.contact')),
                ('undone_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_series_undone', to='contact.contact')),
                ('visible_to_ministries', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='%(class)s_audience', to='org.ministry', verbose_name="Only these ministries' staff")),
            ],
            options={
                'verbose_name_plural': 'event series',
                'ordering': ['-starts_on', 'name'],
            },
            bases=(core.constraints.ConstraintErrorFieldMixin, models.Model),
        ),
        migrations.AddField(
            model_name='event',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occasions', to='events.eventseries'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='series',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.eventseries'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('series__isnull', False)), fields=('series', 'start_time'), name='event_one_occasion_per_series_moment', violation_error_code='event_series_moment_taken', violation_error_message='This series already has an occasion at that moment.'),
        ),
        migrations.AddField(
            model_name='eventseriesrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='events.participationrole'),
        ),
        migrations.AddField(
            model_name='eventseriesrole',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='events.eventseries'),
        ),
        migrations.AddField(
            model_name='eventseriesrole',
            name='visible_to_ministries',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='%(class)s_audience', to='org.ministry', verbose_name="Only these ministries' staff"),
        ),
        migrations.AddField(
            model_name='historicaleventseries',
            name='generated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contact.contact'),
        ),
        migrations.AddField(
            model_name='historicaleventseries',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaleventseries',
            name='ministry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='org.ministry'),
        ),
        migrations.AddField(
            model_name='historicaleventseries',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contact.contact'),
        ),
        migrations.AddField(
            model_name='historicaleventseries',
            name='undone_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contact.contact'),
        ),
        migrations.AddField(
            model_name='historicaleventseries_visible_to_ministries',
            name='eventseries',
            field=models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.eventseries'),
        ),
        migrations.AddField(
            model_name='historicaleventseries_visible_to_ministries',
            name='history',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='events.historicaleventseries'),
        ),
        migrations.AddField(
            model_name='historicaleventseries_visible_to_ministries',
            name='ministry',
            field=models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='org.ministry'),
        ),
        migrations.AddField(
            model_name='historicaleventseriesrole',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaleventseriesrole',
            name='role',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.participationrole'),
        ),
        migrations.AddField(
            model_name='historicaleventseriesrole',
            name='series',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.eventseries'),
        ),
        migrations.AddField(
            model_name='historicaleventseriesrole_visible_to_ministries',
            name='eventseriesrole',
            field=models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.eventseriesrole'),
        ),
        migrations.AddField(
            model_name='historicaleventseriesrole_visible_to_ministries',
            name='history',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='events.historicaleventseriesrole'),
        ),
        migrations.AddField(
            model_name='historicaleventseriesrole_visible_to_ministries',
            name='ministry',
            field=models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='org.ministry'),
        ),
        migrations.AddConstraint(
            model_name='eventseries',
            constraint=models.CheckConstraint(condition=models.Q(('duration__gt', datetime.timedelta(0))), name='eventseries_duration_is_positive', violation_error_code='eventseries_duration_not_positive', violation_error_message='Say how long each occasion runs — it has to be more than nothing.'),
        ),
        migrations.AddConstraint(
            model_name='eventseriesrole',
            constraint=models.UniqueConstraint(fields=('series', 'role'), name='eventseriesrole_unique_per_series', violation_error_code='eventseriesrole_duplicate', violation_error_message='This series already opens that role on every occasion.'),
        ),
        migrations.AddConstraint(
            model_name='eventseriesrole',
            constraint=models.CheckConstraint(condition=models.Q(('needed_count__isnull', True), ('needed_count__gt', 0), _connector='OR'), name='eventseriesrole_needed_count_is_positive', violation_error_code='eventseriesrole_needed_count_not_positive', violation_error_message='Leave the number empty for no limit; otherwise it has to be at least 1.'),
        ),
    ]
