# Generated by Django 5.2.16 on 2026-09-15 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_contact_contact_individual_has_a_first_name'),
        ('events', '0028_event_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='time updated')),
                ('token', models.CharField(max_length=43, unique=True, verbose_name='subscription token')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_feed', to='contact.contact', verbose_name='whose calendar')),
            ],
            options={
                'verbose_name': 'calendar feed',
                'verbose_name_plural': 'calendar feeds',
            },
        ),
    ]
