# Generated by Django 5.2.16 on 2026-09-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_event_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseries',
            name='address_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='address_state',
            field=models.CharField(blank=True, max_length=100, verbose_name='state / province / region'),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='address_street',
            field=models.CharField(blank=True, help_text='Copied onto each occasion as it is made.', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaleventseries',
            name='address_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicaleventseries',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='historicaleventseries',
            name='address_state',
            field=models.CharField(blank=True, max_length=100, verbose_name='state / province / region'),
        ),
        migrations.AddField(
            model_name='historicaleventseries',
            name='address_street',
            field=models.CharField(blank=True, help_text='Copied onto each occasion as it is made.', max_length=255),
        ),
    ]
