"""`EventGrant`：谁被指名管理**这一场**活动 —— ministry 和 foundation 之间的第三档。

⭐ 不是 `MinistryRole` 上的一个新档位，而 [D20](../../docs/planning/decisions/D20-ministry-role.md)
   自己的判据说清了为什么：那一条的测试是「这句话里有没有『某个 ministry 的』？」
   而「某**一场活动**的完全管理权」过不了那个判据 —— 它比一个 ministry 窄。
   全文见 D47。

⚠️ 两张表，因为它带 simple-history：一次授权是要有人负责的事，而
   「去年三月谁能看这场活动的报名」是会被问到的。

⚠️ 无数据迁移，也不可能有：这张表在此之前不存在，没有任何一行要回填。
"""

# Generated by Django 5.2.16 on 2026-09-16 01:17

import core.constraints
import core.querysets
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_contact_contact_individual_has_a_first_name'),
        ('events', '0031_event_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEventGrant',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='time created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='time updated')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contact', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contact.contact')),
                ('event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.event')),
                ('granted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical event grant',
                'verbose_name_plural': 'historical event grants',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EventGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='time updated')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_grants', to='contact.contact')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='events.event')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', 'contact'],
                'indexes': [models.Index(fields=['contact', 'end_date'], name='events_even_contact_f92e5f_idx')],
                'constraints': [models.UniqueConstraint(fields=('contact', 'event', 'start_date'), name='eventgrant_unique_grant', nulls_distinct=False, violation_error_code='eventgrant_duplicate_grant', violation_error_message='They already have this event from that date.'), models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='eventgrant_end_date_not_before_start_date', violation_error_code='eventgrant_end_before_start', violation_error_message='The end date cannot be before the start date.')],
            },
            bases=(core.constraints.ConstraintErrorFieldMixin, core.querysets.DateRangeMixin, models.Model),
        ),
    ]
