# Generated by Django 5.2.16 on 2026-09-18 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_exclusion_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventgrant',
            options={'ordering': ['-start_date', 'contact', '-pk']},
        ),
    ]
