# Generated by Django 5.2.16 on 2026-08-05 23:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, help_text='Full-screen background. Landscape, at least 2000px wide.', upload_to='home')),
                ('hero_video', models.FileField(blank=True, help_text='Optional, and used instead of the image when set. It plays muted and on a loop — browsers refuse to autoplay sound, and a page that made noise on arrival would be worse anyway. Keep it under 10 MB: every visitor downloads all of it.', upload_to='home', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm'])])),
                ('verse_text', models.TextField(blank=True, help_text='The passage itself. Shown first, in large type.')),
                ('verse_reference', models.CharField(blank=True, help_text='Where it is from, shown underneath — e.g. Colossians 3:23–24.', max_length=120)),
            ],
            options={
                'verbose_name': 'home page',
                'verbose_name_plural': 'home page',
            },
        ),
    ]
