# Generated by Django 5.2.16 on 2026-08-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_home_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='brand_palette',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
