# Generated by Django 5.2.16 on 2026-08-07 06:47

import core.storages
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cache_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Full-screen background. Landscape, at least 2000px wide.', storage=core.storages.public_storage, upload_to='home'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Optional, and used instead of the image when set. It plays muted and on a loop — browsers refuse to autoplay sound, and a page that made noise on arrival would be worse anyway. Keep it under 10 MB: every visitor downloads all of it.', storage=core.storages.public_storage, upload_to='home', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm'])]),
        ),
    ]
