# Generated by Django 5.2.16 on 2026-08-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_homepage_hero_image_alter_homepage_hero_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_focus_x',
            field=models.PositiveSmallIntegerField(default=50, help_text='0 is the left edge, 100 the right. 50 keeps the middle — raise it to save something on the right of the picture.', verbose_name='focus, across'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_focus_y',
            field=models.PositiveSmallIntegerField(default=50, help_text='0 is the top edge, 100 the bottom. 50 keeps the middle — lower it (towards 0) to stop faces being cut off the top.', verbose_name='focus, down'),
        ),
        migrations.AddConstraint(
            model_name='homepage',
            constraint=models.CheckConstraint(condition=models.Q(('hero_focus_x__lte', 100), ('hero_focus_y__lte', 100)), name='homepage_hero_focus_within_the_picture', violation_error_code='homepage_focus_out_of_range', violation_error_message='The focus has to be between 0 and 100 — it is a position inside the picture.'),
        ),
    ]
