# Generated by Django 5.2.16 on 2026-08-31 20:22

import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_homepage_hero_focus_x_homepage_hero_focus_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_image_1280',
            field=models.ImageField(blank=True, editable=False, storage=core.storages.public_storage, upload_to='home'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image_1920',
            field=models.ImageField(blank=True, editable=False, storage=core.storages.public_storage, upload_to='home'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image_2560',
            field=models.ImageField(blank=True, editable=False, storage=core.storages.public_storage, upload_to='home'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image_height',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image_width',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
