# Generated by Django 5.2.16 on 2026-08-07 08:41

import core.storages
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0006_text_length_limits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='time updated')),
                ('image', models.ImageField(storage=core.storages.memories_storage, upload_to='gallery')),
                ('thumb', models.ImageField(height_field='thumb_height', storage=core.storages.memories_storage, upload_to='gallery', width_field='thumb_width')),
                ('thumb_width', models.PositiveIntegerField(editable=False)),
                ('thumb_height', models.PositiveIntegerField(editable=False)),
                ('image_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('taken_year', models.PositiveSmallIntegerField()),
                ('ministry', models.ForeignKey(blank=True, help_text='Leave empty for a foundation-wide photo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gallery_photos', to='org.ministry')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'gallery photo',
                'verbose_name_plural': 'gallery photos',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['-created_at'], name='gallery_gal_created_4fd225_idx'), models.Index(fields=['ministry', '-created_at'], name='gallery_gal_ministr_d69a00_idx')],
            },
        ),
    ]
