# Generated by Django 5.2.16 on 2026-07-27 21:41

import django.db.models.deletion
import django_countries.fields
import localflavor.us.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages_plus', '0004_auto_20171214_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_a_to_b', models.CharField(max_length=100)),
                ('name_b_to_a', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='time updated')),
                ('contact_type', models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], db_index=True, default='individual', max_length=20)),
                ('legal_first_name', models.CharField(blank=True, max_length=100)),
                ('legal_last_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('organization_name', models.CharField(blank=True, help_text='Used when contact_type is organization.', max_length=200)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='US')),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('unspecified', 'Prefer not to say')], max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('preferred_communication_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('mail', 'Postal mail')], max_length=20)),
                ('address_street', models.CharField(blank=True, max_length=255)),
                ('address_city', models.CharField(blank=True, max_length=100)),
                ('address_state', localflavor.us.models.USStateField(blank=True, max_length=2)),
                ('address_postal_code', models.CharField(blank=True, max_length=20)),
                ('address_country', django_countries.fields.CountryField(blank=True, default='US', max_length=2)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('preferred_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='languages_plus.language')),
            ],
            options={
                'ordering': ['legal_last_name', 'legal_first_name'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='time updated')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('contact_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_a', to='contact.contact')),
                ('contact_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_b', to='contact.contact')),
                ('relationship_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationships', to='contact.relationshiptype')),
            ],
            options={
                'indexes': [models.Index(fields=['contact_a', 'relationship_type'], name='contact_rel_contact_26cdbc_idx'), models.Index(fields=['contact_b', 'relationship_type'], name='contact_rel_contact_60c247_idx')],
            },
        ),
    ]
