# Generated by Django 5.2.16 on 2026-07-31 19:52

import core.constraints
import core.models
import django.db.models.deletion
import django.db.models.functions.text
import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='ISO 639-3 code')),
                ('name', models.CharField(help_text='Official ISO 639-3 name.', max_length=150)),
                ('display_name', models.CharField(db_index=True, help_text='Name shown in dropdowns. Defaults to the ISO name.', max_length=150)),
                ('alt_names', models.CharField(blank=True, help_text='Other names this language can be found by, comma separated. Searched but not displayed.', max_length=255)),
                ('language_type', models.CharField(choices=[('L', 'Living'), ('E', 'Extinct'), ('H', 'Historical'), ('C', 'Constructed'), ('S', 'Special')], default='L', max_length=1)),
                ('pin_rank', models.PositiveSmallIntegerField(default=0, help_text='Higher numbers sort to the top of the list. 0 = unpinned.')),
            ],
            options={
                'ordering': ['-pin_rank', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='time updated')),
                ('contact_type', models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], db_index=True, default='individual', max_length=20)),
                ('legal_first_name', models.CharField(blank=True, max_length=100)),
                ('legal_last_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('organization_name', models.CharField(blank=True, help_text='Used when contact_type is organization.', max_length=200)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, region='US')),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('unspecified', 'Prefer not to say')], max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('preferred_communication_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('mail', 'Postal mail')], max_length=20)),
                ('address_street', models.CharField(blank=True, max_length=255)),
                ('address_city', models.CharField(blank=True, max_length=100)),
                ('address_state', models.CharField(blank=True, max_length=100, verbose_name='state / province / region')),
                ('address_postal_code', models.CharField(blank=True, max_length=20)),
                ('address_country', django_countries.fields.CountryField(blank=True, default='US', max_length=2)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('preferred_language', models.ForeignKey(blank=True, limit_choices_to={'language_type': 'L'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contact.language')),
            ],
            options={
                'ordering': ['legal_last_name', 'legal_first_name'],
            },
            bases=(core.constraints.ConstraintErrorFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Stable identifier used by code. Lowercase, cannot be changed later.')),
                ('name_a_to_b', models.CharField(max_length=100)),
                ('name_b_to_a', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_symmetric', models.BooleanField(default=False, help_text='The relationship reads the same in both directions (spouse, sibling).')),
                ('usable_as_emergency_contact', models.BooleanField(default=False, help_text='Offer this type when recording an emergency contact.')),
            ],
            options={
                'ordering': ['name_a_to_b'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name_a_to_b')), name='relationshiptype_name_a_to_b_ci_unique', violation_error_code='reltype_name_taken', violation_error_message='A relationship type with this name already exists.'), models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='relationshiptype_code_ci_unique', violation_error_code='reltype_code_taken', violation_error_message='A relationship type with this code already exists.')],
            },
            bases=(core.models.ImmutableCodeMixin, core.constraints.ConstraintErrorFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='time updated')),
                ('name', models.CharField(max_length=200)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='US')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='contact.contact')),
                ('relationship_type', models.ForeignKey(help_text='读作「紧急联系人 是 本人 的 ___」。例：小明名下填「王秀英」+「母亲」= 王秀英是小明的母亲。', limit_choices_to={'usable_as_emergency_contact': True}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contact.relationshiptype')),
            ],
            options={
                'ordering': ['person', 'name'],
            },
            bases=(core.constraints.ConstraintErrorFieldMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contact_type', 'individual'), _negated=True), models.Q(('legal_last_name', ''), _negated=True), _connector='OR'), name='contact_individual_has_a_last_name', violation_error_code='individual_needs_last_name', violation_error_message='An individual needs a legal last name.'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contact_type', 'organization'), _negated=True), models.Q(('organization_name', ''), _negated=True), _connector='OR'), name='contact_organization_has_a_name', violation_error_code='organization_needs_name', violation_error_message='An organization needs an organization name.'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(('contact_type__in', ['individual', 'organization'])), name='contact_type_is_known', violation_error_code='contact_type_unknown', violation_error_message='Unknown contact type.'),
        ),
        migrations.AddConstraint(
            model_name='emergencycontact',
            constraint=models.UniqueConstraint(models.F('person'), django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), models.F('phone'), name='emergencycontact_unique_per_person', violation_error_code='emergency_contact_duplicate', violation_error_message='This emergency contact is already recorded for them.'),
        ),
    ]
