# Generated by Django 5.2.16 on 2026-07-27 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='ISO 639-3 code')),
                ('name', models.CharField(help_text='Official ISO 639-3 name.', max_length=150)),
                ('display_name', models.CharField(db_index=True, help_text='Name shown in dropdowns. Defaults to the ISO name.', max_length=150)),
                ('alt_names', models.CharField(blank=True, help_text='Other names this language can be found by, comma separated. Searched but not displayed.', max_length=255)),
                ('language_type', models.CharField(choices=[('L', 'Living'), ('E', 'Extinct'), ('H', 'Historical'), ('C', 'Constructed'), ('S', 'Special')], default='L', max_length=1)),
                ('pin_rank', models.PositiveSmallIntegerField(default=0, help_text='Higher numbers sort to the top of the list. 0 = unpinned.')),
            ],
            options={
                'ordering': ['-pin_rank', 'display_name'],
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_state',
            field=models.CharField(blank=True, max_length=100, verbose_name='state / province / region'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='preferred_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contact.language'),
        ),
    ]
