# Generated by Django 5.2.16 on 2026-07-31 19:52

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_seed_languages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalContact',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='time created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='time updated')),
                ('contact_type', models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], db_index=True, default='individual', max_length=20)),
                ('legal_first_name', models.CharField(blank=True, max_length=100)),
                ('legal_last_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('organization_name', models.CharField(blank=True, help_text='Used when contact_type is organization.', max_length=200)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, region='US')),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('unspecified', 'Prefer not to say')], max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('preferred_communication_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('mail', 'Postal mail')], max_length=20)),
                ('address_street', models.CharField(blank=True, max_length=255)),
                ('address_city', models.CharField(blank=True, max_length=100)),
                ('address_state', models.CharField(blank=True, max_length=100, verbose_name='state / province / region')),
                ('address_postal_code', models.CharField(blank=True, max_length=20)),
                ('address_country', django_countries.fields.CountryField(blank=True, default='US', max_length=2)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('preferred_language', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'language_type': 'L'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contact.language')),
            ],
            options={
                'verbose_name': 'historical contact',
                'verbose_name_plural': 'historical contacts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
