# Generated by Django 5.2.16 on 2026-07-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_seed_languages'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contact_type', 'individual'), models.Q(('legal_last_name', ''), _negated=True)), models.Q(('contact_type', 'organization'), models.Q(('organization_name', ''), _negated=True)), _connector='OR'), name='contact_name_matches_type', violation_error_message='An individual needs a legal last name; an organization needs an organization name.'),
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.CheckConstraint(condition=models.Q(('contact_a', models.F('contact_b')), _negated=True), name='relationship_no_self_reference', violation_error_message='A contact cannot be related to themselves.'),
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('contact_a', 'contact_b', 'relationship_type', 'start_date'), name='relationship_unique_per_type_and_start', nulls_distinct=False, violation_error_message='This relationship has already been recorded.'),
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='relationship_end_date_not_before_start_date', violation_error_message='The end date cannot be before the start date.'),
        ),
    ]
