# Generated by Django 5.2.16 on 2026-07-27 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_seed_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='preferred_language',
            field=models.ForeignKey(blank=True, limit_choices_to={'language_type': 'L'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contact.language'),
        ),
    ]
