# Generated by Django 5.2.16 on 2026-07-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_historicalcontact'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='contact_name_matches_type',
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contact_type', 'individual'), _negated=True), models.Q(('legal_last_name', ''), _negated=True), _connector='OR'), name='contact_individual_has_a_last_name', violation_error_code='individual_needs_last_name', violation_error_message='An individual needs a legal last name.'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contact_type', 'organization'), _negated=True), models.Q(('organization_name', ''), _negated=True), _connector='OR'), name='contact_organization_has_a_name', violation_error_code='organization_needs_name', violation_error_message='An organization needs an organization name.'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(('contact_type__in', ['individual', 'organization'])), name='contact_type_is_known', violation_error_code='contact_type_unknown', violation_error_message='Unknown contact type.'),
        ),
        migrations.AlterConstraint(
            model_name='relationship',
            name='relationship_no_self_reference',
            constraint=models.CheckConstraint(condition=models.Q(('contact_a', models.F('contact_b')), _negated=True), name='relationship_no_self_reference', violation_error_code='relationship_self_reference', violation_error_message='A contact cannot be related to themselves.'),
        ),
        migrations.AlterConstraint(
            model_name='relationship',
            name='relationship_unique_per_type_and_start',
            constraint=models.UniqueConstraint(fields=('contact_a', 'contact_b', 'relationship_type', 'start_date'), name='relationship_unique_per_type_and_start', nulls_distinct=False, violation_error_code='relationship_already_recorded', violation_error_message='This relationship has already been recorded.'),
        ),
        migrations.AlterConstraint(
            model_name='relationship',
            name='relationship_end_date_not_before_start_date',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='relationship_end_date_not_before_start_date', violation_error_code='relationship_end_before_start', violation_error_message='The end date cannot be before the start date.'),
        ),
    ]
