# Generated by Django 5.2.16 on 2026-07-29 03:41

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_remove_contact_contact_name_matches_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationshiptype',
            options={'ordering': ['name_a_to_b']},
        ),
        # goal.md prescribes a three-migration dance for adding a unique non-null
        # column (add nullable -> backfill -> tighten). That is the procedure for
        # a table with data in it; RelationshipType measured 0 rows (02-roadmap
        # B0), so one migration does it. makemigrations still asks for a one-off
        # default because it reads the schema, not the data: default='' below is
        # that answer and applies to no row. preserve_default=False keeps it out
        # of the model state — an empty code is NOT an acceptable value.
        migrations.AddField(
            model_name='relationshiptype',
            name='code',
            field=models.SlugField(default='', help_text='Stable identifier used by code. Lowercase, cannot be changed later.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationshiptype',
            name='is_symmetric',
            field=models.BooleanField(default=False, help_text='The relationship reads the same in both directions (spouse, sibling).'),
        ),
        migrations.AddField(
            model_name='relationshiptype',
            name='usable_as_emergency_contact',
            field=models.BooleanField(default=False, help_text='Offer this type when recording an emergency contact.'),
        ),
        migrations.AddConstraint(
            model_name='relationshiptype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name_a_to_b')), name='relationshiptype_name_a_to_b_ci_unique', violation_error_code='reltype_name_taken', violation_error_message='A relationship type with this name already exists.'),
        ),
        migrations.AddConstraint(
            model_name='relationshiptype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='relationshiptype_code_ci_unique', violation_error_code='reltype_code_taken', violation_error_message='A relationship type with this code already exists.'),
        ),
    ]
