# Generated by Django 5.2.16 on 2026-08-03 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_relationship_names_read_as_a_noun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='relationship_type',
            field=models.ForeignKey(help_text="Read it as a sentence: “Wang Xiuying is this person's parent.” Pick what the emergency contact is to them, not the other way round.", limit_choices_to={'usable_as_emergency_contact': True}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contact.relationshiptype'),
        ),
    ]
