# Generated by Django 5.2.16 on 2026-07-29 03:46

import datetime
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_relationshiptype_options_relationshiptype_code_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='relationship',
            name='relationship_unique_per_type_and_start',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='is_active',
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(django.db.models.functions.comparison.Least('contact_a', 'contact_b'), django.db.models.functions.comparison.Greatest('contact_a', 'contact_b'), models.F('relationship_type'), django.db.models.functions.comparison.Coalesce('start_date', models.Value(datetime.date(1, 1, 1))), name='relationship_unique_unordered_pair', violation_error_code='relationship_already_recorded', violation_error_message='This relationship has already been recorded.'),
        ),
    ]
