# Generated by Django 5.2.16 on 2026-07-29 03:52

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_remove_relationship_relationship_unique_per_type_and_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, region='US'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, region='US'),
        ),
    ]
