"""个人必须有 first name —— 和 last name 那条同一个形状（2026-08-19）。

⚠️ **这条迁移会在数据不干净时当场失败**，而且那正是它该做的事：Postgres 加
   CHECK 约束时要验一遍现有行，任何一行 `contact_type='individual'` 且
   `legal_first_name=''` 都会让 ALTER TABLE 报错、整条迁移回滚。

   先跑一次看看有没有：

       Contact.objects.filter(contact_type="individual", legal_first_name="")

   补名字的地方是 admin。**不要**在这里写一段 RunPython 自动填上 ——
   名字是真实信息，没有任何自动值是对的，而填进去的占位符事后分不出来。
   （2026-08-19 本地库：0 行。线上库当时全是测试账号，上线前整个 schema 会清。）

⚠️ 约束只管 `individual`。机构（`organization`）没有姓也没有名，用 `organization_name`。
"""

# Generated by Django 5.2.16 on 2026-08-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_text_length_limits'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contact_type', 'individual'), _negated=True), models.Q(('legal_first_name', ''), _negated=True), _connector='OR'), name='contact_individual_has_a_first_name', violation_error_code='individual_needs_first_name', violation_error_message='An individual needs a legal first name.'),
        ),
    ]
