# Generated by Django 5.2.16 on 2026-07-29 03:53

import core.constraints
import django.db.models.deletion
import django.db.models.functions.text
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_alter_contact_phone_alter_historicalcontact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='time updated')),
                ('name', models.CharField(max_length=200)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='US')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='contact.contact')),
                ('relationship_type', models.ForeignKey(help_text='读作「紧急联系人 是 本人 的 ___」。例：小明名下填「王秀英」+「母亲」= 王秀英是小明的母亲。', limit_choices_to={'usable_as_emergency_contact': True}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contact.relationshiptype')),
            ],
            options={
                'ordering': ['person', 'name'],
                'constraints': [models.UniqueConstraint(models.F('person'), django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), models.F('phone'), name='emergencycontact_unique_per_person', violation_error_code='emergency_contact_duplicate', violation_error_message='This emergency contact is already recorded for them.')],
            },
            bases=(core.constraints.ConstraintErrorFieldMixin, models.Model),
        ),
    ]
