"""邮箱验证：User.email_verified + 一张 EmailVerification 表（2026-08-19）。

⚠️ **新列默认 False，而现有账号在这里被标成已验证。** 两件事都要，而且不矛盾：

   - 默认 False 是给**以后**的每一条建号路径用的 —— 不写就是安全的那一边。
   - 现有行标成 True 是因为它们全是测试账号（2026-08-19 与需求方确认，上线前
     整个 schema 会清空重来）。不标的话，这一次部署会把现在能登录的每一个人
     锁在门外，而他们收到的信息只会是「你的邮箱还没验证」，没有任何上下文说
     为什么昨天还好好的。

   ⚠️ 如果这条迁移是在**已有真实用户**的库上跑的，先想清楚这一段：那时候正确的
      做法可能是反过来（全部标 False，逼所有人验一次），而那是一个产品决定，
      不是一条迁移能替人做的。

⚠️ 验证码存的是**哈希**，不是明文。六位数只有一百万种，所以哈希不是护城河 ——
   真正的防线是 15 分钟有效期加 5 次尝试上限。它买到的是：备份、psql、
   带着一行数据的报错页，都不会顺手交给别人一个还能用的码。
"""

# Generated by Django 5.2.16 on 2026-08-19 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing_accounts_verified(apps, schema_editor):
    """把这条迁移**之前**就存在的账号标成已验证 —— 理由写在文件头。

    ⚠️ 逆向是 noop 而不是「全部标回 False」：回滚这条迁移会把整列删掉，
       没有什么可以还原的；而写一个「全部标 False」的逆向函数，会在有人
       只是想临时回退时，静默地把真正验证过的账号也降级。
    """
    User = apps.get_model("accounts", "User")
    User.objects.update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_email_is_the_login_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Whether the person proved they can read mail at this address.', verbose_name='email address verified'),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='time updated')),
                ('email', models.EmailField(max_length=254)),
                ('code_hash', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_em_user_id_1b4ad5_idx')],
            },
        ),
        migrations.RunPython(
            mark_existing_accounts_verified, migrations.RunPython.noop),
    ]
