# Generated by Django 5.2.16 on 2026-08-31 19:40

import core.constraints
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0009_contact_contact_individual_has_a_first_name'),
        ('org', '0008_kind_to_staff_and_compensation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalNotice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='time created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='time updated')),
                ('visible_to_outsiders', models.BooleanField(default=False, help_text='Outside volunteers and the people the foundation serves.', verbose_name='People with no current post')),
                ('visible_to_all_staff', models.BooleanField(default=False, help_text='Anyone holding a post on the day — paid or not.', verbose_name='Everybody on the books')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('starts_showing', models.DateTimeField(help_text='When people start seeing it. Now, unless you are writing ahead of time.', verbose_name='Goes up')),
                ('stops_showing', models.DateTimeField(help_text='It stops showing after this, and moves to the past notices list. Nothing is deleted.', verbose_name='Comes down')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='org.ministry')),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contact.contact')),
            ],
            options={
                'verbose_name': 'historical notice',
                'verbose_name_plural': 'historical notices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='time updated')),
                ('visible_to_outsiders', models.BooleanField(default=False, help_text='Outside volunteers and the people the foundation serves.', verbose_name='People with no current post')),
                ('visible_to_all_staff', models.BooleanField(default=False, help_text='Anyone holding a post on the day — paid or not.', verbose_name='Everybody on the books')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('starts_showing', models.DateTimeField(help_text='When people start seeing it. Now, unless you are writing ahead of time.', verbose_name='Goes up')),
                ('stops_showing', models.DateTimeField(help_text='It stops showing after this, and moves to the past notices list. Nothing is deleted.', verbose_name='Comes down')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notices', to='org.ministry')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notices_owned', to='contact.contact')),
                ('visible_to_ministries', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='%(class)s_audience', to='org.ministry', verbose_name="Only these ministries' staff")),
            ],
            options={
                'ordering': ['-starts_showing', '-id'],
                'indexes': [models.Index(fields=['status', 'stops_showing', 'starts_showing'], name='notices_not_status_a18fa9_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('stops_showing__gt', models.F('starts_showing'))), name='notice_comes_down_after_it_goes_up', violation_error_code='notice_window_backwards', violation_error_message='A notice has to come down after it goes up.')],
            },
            bases=(core.constraints.ConstraintErrorFieldMixin, models.Model),
        ),
    ]
