# Generated by Django 5.2.16 on 2026-09-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    """Wording only: the help text under "People with no current post".

    It said "Outside volunteers and the people the foundation serves", and
    "volunteers" is the one word participants.md section 5 keeps for group A —
    somebody giving their own time. On this box it meant group B as well, so the
    tick read as "tick this to recruit volunteers" on the very control whose
    point is that it also covers the people the foundation serves.

    ⚠️ No column changes, no data changes. It exists because help_text is part
       of the field's deconstruction, and NoMissingMigrationsTests would go red
       without it — which is the guard doing its job on the cheapest possible
       case.
    """


    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnotice',
            name='visible_to_outsiders',
            field=models.BooleanField(default=False, help_text='People from outside the foundation — including the people it serves.', verbose_name='People with no current post'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='visible_to_outsiders',
            field=models.BooleanField(default=False, help_text='People from outside the foundation — including the people it serves.', verbose_name='People with no current post'),
        ),
    ]
