# Generated by Django 5.2.16 on 2026-07-29 19:41

import core.constraints
import core.models
import django.db.models.deletion
import django.db.models.functions.text
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Stable identifier used by code. Lowercase, cannot be changed later.')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='employmenttype_code_ci_unique', violation_error_code='employmenttype_code_taken', violation_error_message='An employment type with this code already exists.')],
            },
            bases=(core.models.ImmutableCodeMixin, core.constraints.ConstraintErrorFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='time updated')),
                ('code', models.SlugField(help_text='Stable identifier used by code. Lowercase, cannot be changed later.')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('founded_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'ministries',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='ministry_code_ci_unique', violation_error_code='ministry_code_taken', violation_error_message='A ministry with this code already exists.')],
            },
            bases=(core.models.ImmutableCodeMixin, core.constraints.ConstraintErrorFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='time updated')),
                ('code', models.SlugField(help_text='Stable identifier used by code. Lowercase, cannot be changed later.')),
                ('name', models.CharField(help_text='e.g. "Program Director".', max_length=100)),
                ('kind', models.CharField(choices=[('employee', 'Employee'), ('volunteer', 'Volunteer'), ('board', 'Board member')], default='volunteer', max_length=20)),
                ('is_leader', models.BooleanField(default=False, help_text='Read by code when grouping the chart. The title is for humans.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the post still exists. Nothing to do with anybody holding it.')),
                ('description', models.TextField(blank=True)),
                ('ministry', models.ForeignKey(blank=True, help_text='Leave empty for foundation-wide posts such as Executive Director.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='org.ministry')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_reports', to='org.position')),
            ],
            options={
                'ordering': ['ministry__name', '-is_leader', 'name'],
            },
            bases=(core.models.ImmutableCodeMixin, core.constraints.ConstraintErrorFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPosition',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='time created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='time updated')),
                ('code', models.SlugField(help_text='Stable identifier used by code. Lowercase, cannot be changed later.')),
                ('name', models.CharField(help_text='e.g. "Program Director".', max_length=100)),
                ('kind', models.CharField(choices=[('employee', 'Employee'), ('volunteer', 'Volunteer'), ('board', 'Board member')], default='volunteer', max_length=20)),
                ('is_leader', models.BooleanField(default=False, help_text='Read by code when grouping the chart. The title is for humans.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the post still exists. Nothing to do with anybody holding it.')),
                ('description', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(blank=True, db_constraint=False, help_text='Leave empty for foundation-wide posts such as Executive Director.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='org.ministry')),
                ('reports_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='org.position')),
            ],
            options={
                'verbose_name': 'historical position',
                'verbose_name_plural': 'historical positions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['ministry', 'kind', 'is_active'], name='org_positio_ministr_03df01_idx'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.CheckConstraint(condition=models.Q(('reports_to', models.F('id')), _negated=True), name='position_reports_to_is_not_self', violation_error_code='position_reports_to_self', violation_error_message='A position cannot report to itself.'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='position_code_ci_unique', violation_error_code='position_code_taken', violation_error_message='A position with this code already exists.'),
        ),
    ]
