# Generated by Django 5.2.16 on 2026-07-30 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_emergencycontact'),
        ('org', '0002_historicalassignment_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='contact.contact'),
        ),
    ]
