# Generated by Django 5.2.16 on 2026-07-30 23:36

import core.constraints
import core.querysets
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_seed_languages'),
        ('org', '0003_alter_assignment_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMinistryRole',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='time created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='time updated')),
                ('role', models.CharField(choices=[('admin', 'Ministry admin'), ('coordinator', 'Coordinator')], default='admin', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contact', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contact.contact')),
                ('granted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='org.ministry')),
            ],
            options={
                'verbose_name': 'historical ministry role',
                'verbose_name_plural': 'historical ministry roles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MinistryRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='time updated')),
                ('role', models.CharField(choices=[('admin', 'Ministry admin'), ('coordinator', 'Coordinator')], default='admin', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ministry_roles', to='contact.contact')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='org.ministry')),
            ],
            options={
                'ordering': ['ministry__name', 'contact'],
                'indexes': [models.Index(fields=['contact', 'end_date'], name='org_ministr_contact_47ad9b_idx')],
                'constraints': [models.UniqueConstraint(fields=('contact', 'ministry', 'role', 'start_date'), name='ministryrole_unique_grant', nulls_distinct=False, violation_error_code='ministryrole_duplicate_grant', violation_error_message='They already have that role in this ministry from that date.'), models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='ministryrole_end_date_not_before_start_date', violation_error_code='ministryrole_end_before_start', violation_error_message='The end date cannot be before the start date.')],
            },
            bases=(core.constraints.ConstraintErrorFieldMixin, core.querysets.DateRangeMixin, models.Model),
        ),
    ]
