# Generated by Django 5.2.16 on 2026-08-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_historicalministryrole_ministryrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='website',
            field=models.URLField(blank=True, help_text="Optional. If this ministry has a page of its own, events will link to it from the ministry's name."),
        ),
    ]
