"""Schema half of the axis split: add `compensation`, narrow `kind` (D32).

Two migrations, not one, and the split is deliberate: when something goes wrong
the data half can be rolled back on its own. What makes that possible is a
Django fact worth stating, because it is what makes the state between these two
migrations safe rather than broken — `choices` never reaches Postgres. A
CharField gets no CHECK and no enum type, so between this migration and 0008
the table still holds "employee" / "volunteer", every read and write works, and
only get_kind_display() shows the raw value back.

⚠️ Four operations, because Position carries simple-history. The two on
   `historicalposition` are not noise: 0008 runs the same mapping over both
   tables, and leaving the shadow table out would produce rows reading
   "employee" + "unpaid" — two columns contradicting each other, and looking
   like a fact while they do it.
"""

# Generated by Django 5.2.16 on 2026-08-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_text_length_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalposition',
            name='compensation',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('stipend', 'Stipend')], default='unpaid', help_text='Whether this post is paid. Unpaid staff are still staff.', max_length=20),
        ),
        migrations.AddField(
            model_name='position',
            name='compensation',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('stipend', 'Stipend')], default='unpaid', help_text='Whether this post is paid. Unpaid staff are still staff.', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalposition',
            name='kind',
            field=models.CharField(choices=[('staff', 'Staff'), ('board', 'Board member')], default='staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='kind',
            field=models.CharField(choices=[('staff', 'Staff'), ('board', 'Board member')], default='staff', max_length=20),
        ),
    ]
