"""`Position.needs_foundation_review`：ministry admin 建的岗位还差两格没人确认。

⚠️ **无回填，而 `False` 正是这句话的意思。** 今天库里每一个岗位都是 superuser
   在 Django admin 里建的 —— 他两列都填得了，所以没有一个在等人确认。
   给既有行回填 `True` 会凭空造出一批待办，而那批待办没有人要做。

   （同 `events` 那次给 `Session` 建表时的口径：不回填，而「没有这些行」不是
   遗漏，就是当时的事实。）

⚠️ 两个 operation，因为 `Position` 带 simple-history。影子表那一个不是噪音 ——
   少了它，历史行读出来会缺这一列，而 SimpleHistoryAdmin 的对比视图会在
   「这一版和上一版差在哪」上少答一格。
"""

# Generated by Django 5.2.16 on 2026-09-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0008_kind_to_staff_and_compensation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalposition',
            name='needs_foundation_review',
            field=models.BooleanField(default=False, help_text='Set when a ministry admin created this post: its pay status and reporting line still have to be confirmed by the foundation.', verbose_name='Awaiting foundation review'),
        ),
        migrations.AddField(
            model_name='position',
            name='needs_foundation_review',
            field=models.BooleanField(default=False, help_text='Set when a ministry admin created this post: its pay status and reporting line still have to be confirmed by the foundation.', verbose_name='Awaiting foundation review'),
        ),
    ]
