"""`Position.code` 改成可空 —— 它和另外三张表的 code 不是一回事。

⭐ **一个格子做不了两件事：标识符不许变，描述不许过期。** 从名字自动生成的
   code 看起来像描述、却因为不可改而必然在某次改名之后变成一句假话。所以这一列
   不再试图描述任何东西：默认是空的，只有当真的有别的系统要指向某个岗位时，
   才由人特意设一个锚点（Stripe 的 `lookup_key` / SuccessFactors 的
   `externalCode` 那个形状）。判据和理由写在 `org/models.py` 的 `Position.code` 上。

⚠️ **无数据迁移，而既有的值一个都不动。** `seed_demo` 手挑的那五个
   （`pantry_lead` / `pantry_driver` …）正是这一列现在想要的那种值 ——
   手挑的、有含义的、而且一个都不是 slugify(名字) 会产生的东西。

⚠️ `position_code_ci_unique` 那条约束**一个字不用改**：Postgres 认多个 NULL
   互不相等，所以任意多个没有 code 的岗位可以共存。钉住它的是
   `StaffRosterTests.test_any_number_of_posts_can_have_no_code`。

⚠️ 两个 operation，因为 `Position` 带 simple-history。
"""

# Generated by Django 5.2.16 on 2026-09-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0009_historicalposition_needs_foundation_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalposition',
            name='code',
            field=models.SlugField(blank=True, help_text='Leave empty. Only needed when another system or a script has to refer to this exact post — whoever sets that up knows what to type. Once set it cannot be changed.', null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='code',
            field=models.SlugField(blank=True, help_text='Leave empty. Only needed when another system or a script has to refer to this exact post — whoever sets that up knows what to type. Once set it cannot be changed.', null=True),
        ),
    ]
