"""`needs_foundation_review` 换了含义 —— 只有 help_text 变，列一个字没动。

⭐ 从「那两格还是默认值，等 foundation tier 来填」变成
   **「ministry admin 填了，而 foundation tier 还没核验」**（2026-09-15，用户定的
   流程）。ministry admin 现在填得了薪酬档和汇报线 —— 于是那几格不再是没人声明过
   的默认值，而是一句有人负责的话；核验是第二个人为它签字。

⚠️ **无数据迁移，而那是对的**：这一列上的 `True` 在两种含义下都是「还有人要来看
   一眼这个岗位」，所以既有的行照旧成立。

⚠️ 两个 operation，因为 `Position` 带 simple-history。
"""

# Generated by Django 5.2.16 on 2026-09-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0010_alter_historicalposition_code_alter_position_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalposition',
            name='needs_foundation_review',
            field=models.BooleanField(default=False, help_text="A ministry admin set this post's pay, reporting line or kind, and the foundation has not verified them yet.", verbose_name='Awaiting foundation review'),
        ),
        migrations.AlterField(
            model_name='position',
            name='needs_foundation_review',
            field=models.BooleanField(default=False, help_text="A ministry admin set this post's pay, reporting line or kind, and the foundation has not verified them yet.", verbose_name='Awaiting foundation review'),
        ),
    ]
