# Generated by Django 5.2.16 on 2026-09-18 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0013_exclusion_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-start_date', 'contact', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='ministryrole',
            options={'ordering': ['ministry__name', 'contact', '-pk']},
        ),
    ]
